services:
  - type: web
    name: ecoclean-api
    runtime: docker
    repo: https://github.com/wng3lbballin/ecoclean-store
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        fromDatabase:
          name: ecoclean-db
          property: connectionString
      - key: DATABASE_SSL
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://ecoclean-web.onrender.com

  - type: web
    name: ecoclean-web
    runtime: docker
    repo: https://github.com/wng3lbballin/ecoclean-store
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: BACKEND_HOST
        value: ecoclean-api

databases:
  - name: ecoclean-db
    plan: free
